name: trainsnn
channels:
  - defaults
  - pytorch
  - conda-forge
  - nvidia
  - anaconda
dependencies:
  - python ==3.9
  - pytorch
  - libpng
  - libjpeg
  - torchvision
  - seaborn
  - snntorch
  - cython
  - torchaudio
  - tensorflow
  - keras
  - cudnn
  - cudatoolkit
  - pytorch-cuda=11.8
  - py-xgboost
  - statsmodels
  - matplotlib
  - scikit-learn
  - scipy
  - tqdm
  - bayesian-optimization
