name: trainsnn
channels:
  - defaults
dependencies:
  - torchvision
  - seaborn
  - snntorch
  - cython
  - torchaudio
  - keras
  - cudnn
  - cudatoolkit
  - pytorch-cuda=11.8
  - py-xgboost
  - statsmodels
  - matplotlib
  - scikit-learn
  - scipy
